# Form implementation generated from reading ui file '.\dvrmanager\ui\export_item_widget.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(250, 144)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.export_item_group_box = QtWidgets.QGroupBox(Form)
        self.export_item_group_box.setTitle("")
        self.export_item_group_box.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.export_item_group_box.setFlat(False)
        self.export_item_group_box.setCheckable(True)
        self.export_item_group_box.setObjectName("export_item_group_box")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.export_item_group_box)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.export_item_layout = QtWidgets.QFormLayout()
        self.export_item_layout.setHorizontalSpacing(6)
        self.export_item_layout.setObjectName("export_item_layout")
        self.drive_name_label = QtWidgets.QLabel(self.export_item_group_box)
        self.drive_name_label.setObjectName("drive_name_label")
        self.export_item_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.drive_name_label)
        self.drive_name_edit = QtWidgets.QLineEdit(self.export_item_group_box)
        self.drive_name_edit.setObjectName("drive_name_edit")
        self.export_item_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drive_name_edit)
        self.drive_path_label = QtWidgets.QLabel(self.export_item_group_box)
        self.drive_path_label.setObjectName("drive_path_label")
        self.export_item_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.drive_path_label)
        self.drive_path_edit = QtWidgets.QLineEdit(self.export_item_group_box)
        self.drive_path_edit.setObjectName("drive_path_edit")
        self.export_item_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.drive_path_edit)
        self.unmount_checkbox = QtWidgets.QCheckBox(self.export_item_group_box)
        self.unmount_checkbox.setObjectName("unmount_checkbox")
        self.export_item_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.unmount_checkbox)
        self.delete_checkbox = QtWidgets.QCheckBox(self.export_item_group_box)
        self.delete_checkbox.setObjectName("delete_checkbox")
        self.export_item_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.delete_checkbox)
        self.automatic_checkbox = QtWidgets.QCheckBox(self.export_item_group_box)
        self.automatic_checkbox.setObjectName("automatic_checkbox")
        self.export_item_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.automatic_checkbox)
        self.run_button = QtWidgets.QPushButton(self.export_item_group_box)
        self.run_button.setObjectName("run_button")
        self.export_item_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.run_button)
        self.verticalLayout_6.addLayout(self.export_item_layout)
        self.gridLayout.addWidget(self.export_item_group_box, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.drive_name_label.setText(_translate("Form", "Drive name"))
        self.drive_path_label.setText(_translate("Form", "Drive path"))
        self.unmount_checkbox.setText(_translate("Form", "Unmount"))
        self.delete_checkbox.setText(_translate("Form", "Delete"))
        self.automatic_checkbox.setText(_translate("Form", "Automatic"))
        self.run_button.setText(_translate("Form", "Run"))
