# Form implementation generated from reading ui file '.\dvrmanager\ui\window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 461)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(560, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.settings_group_box.setObjectName("settings_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settings_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.export_items_layout = QtWidgets.QVBoxLayout()
        self.export_items_layout.setSpacing(8)
        self.export_items_layout.setObjectName("export_items_layout")
        self.settings_layout = QtWidgets.QFormLayout()
        self.settings_layout.setObjectName("settings_layout")
        self.target_directory_label = QtWidgets.QLabel(self.settings_group_box)
        self.target_directory_label.setObjectName("target_directory_label")
        self.settings_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.target_directory_label)
        self.target_directory_edit = QtWidgets.QLineEdit(self.settings_group_box)
        self.target_directory_edit.setObjectName("target_directory_edit")
        self.settings_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.target_directory_edit)
        self.export_label_label = QtWidgets.QLabel(self.settings_group_box)
        self.export_label_label.setObjectName("export_label_label")
        self.settings_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.export_label_label)
        self.export_label_edit = QtWidgets.QLineEdit(self.settings_group_box)
        self.export_label_edit.setObjectName("export_label_edit")
        self.settings_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.export_label_edit)
        self.export_items_layout.addLayout(self.settings_layout)
        self.verticalLayout_3.addLayout(self.export_items_layout)
        self.add_export_item_button = QtWidgets.QPushButton(self.settings_group_box)
        self.add_export_item_button.setObjectName("add_export_item_button")
        self.verticalLayout_3.addWidget(self.add_export_item_button)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.settings_group_box)
        self.log_group_box = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_group_box.sizePolicy().hasHeightForWidth())
        self.log_group_box.setSizePolicy(sizePolicy)
        self.log_group_box.setObjectName("log_group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.log_group_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.log_list_widget = QtWidgets.QListWidget(self.log_group_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.log_list_widget.sizePolicy().hasHeightForWidth())
        self.log_list_widget.setSizePolicy(sizePolicy)
        self.log_list_widget.setObjectName("log_list_widget")
        self.verticalLayout.addWidget(self.log_list_widget)
        self.horizontalLayout.addWidget(self.log_group_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.settings_group_box.setTitle(_translate("MainWindow", "Settings"))
        self.target_directory_label.setText(_translate("MainWindow", "Target directory"))
        self.export_label_label.setText(_translate("MainWindow", "Export label"))
        self.add_export_item_button.setText(_translate("MainWindow", "Add"))
        self.log_group_box.setTitle(_translate("MainWindow", "Log"))
